version: 0.0
os: linux
files:
  - source: /takuya-app4
    destination: /var/www/rails/
    overwrite: true
hooks:
  ApplicationStop:
    - location: scripts/restart_server
      timeout: 300
      runas: root