version: 2.1

executors:
  default:
    working_directory: ~/repo
    docker:
      - image: circleci/php:7

commands:
  composer_install_with_cache:
    steps:
      - restore_cache:
          keys:
            - v1-composer-deps-{{ checksum "composer.json" }}
            - v1-composer-deps-
      - run: composer install -n --prefer-dist --working-dir=path/to
      - save_cache:
          key: v1-composer-deps-{{ checksum "composer.json" }}
          paths:
            - ./vendor

jobs:
  checkout_code:
    executor: default
    steps:
      - checkout
      - composer_install_with_cache
      - save_cache: # ソースコードをキャッシュ
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/repo

  test:
    executor: default
    steps:
      - restore_cache: # ソースコードの復元
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}

      - run: phpunit

workflows:
  version: 2
  build:
    jobs:
      - checkout_code
      - test:
          requires: # checkout_codeの後に実行する
            - checkout_code